---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${SA}
imagePullSecrets:
  - name: jfrog-pipelines-sample

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sub-admin
rules:
  - apiGroups: [""]
    resources: ["pods","services","daemonsets","deployments","replicasets","statefulsets","jobs","configmaps","secrets","ingress","serviceaccounts"]
    verbs: ["get","list","create","update","patch", "watch","delete","deletecollection"]
  - apiGroups: ["apps"]
    resources: ["pods","services","daemonsets","deployments","replicasets","statefulsets","jobs","configmaps","secrets","ingress"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sub-admin-rb
subjects:
  - kind: ServiceAccount
    name: ${SA}
roleRef:
  kind: Role
  name: sub-admin
  apiGroup: rbac.authorization.k8s.io